id = "callisto"
name = "Callisto"
version = "0.1.0"
schema_version = 1
authors = ["Callisto contributors"]
description = "Syntax highlighting for Callisto (.cal)."
repository = "https://github.com/brend/callisto"

[grammars.callisto]
repository = "https://github.com/brend/tree-sitter-callisto"
commit = "85b22ef5a45e4c105275a15142426354da755e67"
